
POST http://localhost:7000/user/signup
Content-Type: application/json

{
    "email":"mainaann367@gmail.com",
    "name":"ann",
    "password":"12345678"
}



###
POST http://localhost:7000/user/login
Content-Type: application/json

{
    "email":"collinsfrontend@gmail.com",
    "password":"12345678"
}


###

GET  http://localhost:7000/user/homepage
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMyYjE1NGUyLTA1MzQtNDk1Ni1hZWFkLTQ2NTc4MWEyMDc0YyIsIm5hbWUiOiJ1c2VyMSIsImVtYWlsIjoiam9uYXRoYW5uZGFtYnVraTE2QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwic3RhdHVzIjoiMSIsImlhdCI6MTY2MDMxMzY3OCwiZXhwIjoxNjYwMzE3Mjc4fQ.mkGNs92Dea4gG37Lc6uPn23POKF5jSpNfTRgK8S9bds


###

GET  http://localhost:7000/user/check
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlN2NjMGNmLTIxZDItNDE2My05NjkxLWZmMDM5MTU2N2VhMSIsIm5hbWUiOiJDb2xsaW5zIiwiZW1haWwiOiJjb2xsaW5zQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1OTk1NTA0MiwiZXhwIjoxNjU5OTU4NjQyfQ.x5Ioefpew5PDIEVlMCffzE8zMWbEboK3Oq79pUBhYJA



###
GET  http://localhost:7000/user/users


# projects
###
POST http://localhost:7000/project/newproject
Content-Type: application/json

{
    "name":"project 1",
    "description":"This is project two",
    "end_date": "Aug 12 2022",
    "assigned_user_email":"mainaann367@gmail.com"
}

###
POST http://localhost:7000/project/assignNewProject
Content-Type: application/json

{   "name":"project 1",
    "user_id":"ffba3ac2-e3aa-47af-9575-79db177b2e80"}

###
POST http://localhost:7000/project/deleteProject
Content-Type: application/json

{
    "project_id":"e85a111f-c2a5-4b69-85e6-174306f21fd4"
    }

###
GET  http://localhost:7000/project/projects

###
POST  http://localhost:7000/project/project
Content-Type: application/json

{
    "email": "user3@gmail.com"
}