

POST http://localhost:7000/user/signup
Content-Type: application/json

{
    "email":"collinsfrontend@gmail.com",
    "name":"collo",
    "password":"12345678"
}



###
POST http://localhost:7000/user/login
Content-Type: application/json

{
    "email":"collins@gmail.com",
    "password":"12345678"
}


###

GET  http://localhost:7000/user/homepage
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlN2NjMGNmLTIxZDItNDE2My05NjkxLWZmMDM5MTU2N2VhMSIsIm5hbWUiOiJDb2xsaW5zIiwiZW1haWwiOiJjb2xsaW5zQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1OTk1NzYzOCwiZXhwIjoxNjU5OTYxMjM4fQ.SZbtEsvwYePbqIuSIRuhsl3o3IRk7CeakubzESjiK5Q


###

GET  http://localhost:7000/user/check
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlN2NjMGNmLTIxZDItNDE2My05NjkxLWZmMDM5MTU2N2VhMSIsIm5hbWUiOiJDb2xsaW5zIiwiZW1haWwiOiJjb2xsaW5zQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1OTk1NTA0MiwiZXhwIjoxNjU5OTU4NjQyfQ.x5Ioefpew5PDIEVlMCffzE8zMWbEboK3Oq79pUBhYJA



###
GET  http://localhost:7000/user/users


# projects
###
POST http://localhost:7000/project/newproject
Content-Type: application/json

{
    "name":"project 7",
    "description":"This is project two",
    "end_date": "Aug 12 2022"
}

###
POST http://localhost:7000/project/assignNewProject
Content-Type: application/json

{   "name":"project 7",
    "user_id":"5fa07baa-8a92-4bdd-bc9b-919a7b956fab"}

###
POST http://localhost:7000/project/deleteProject
Content-Type: application/json

{
    "project_id":"9f96064f-f187-4849-a975-1b0e6204b05df"
    }
