
POST http://localhost:7000/user/signup
Content-Type: application/json

{
    "email":"user5@gmail.com",
    "name":"user5",
    "password":"12345678"
}



###
POST http://localhost:7000/user/login
Content-Type: application/json

{
    "email":"user2@gmail.com",
    "password":"12345678"
}


###

GET  http://localhost:7000/user/homepage
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwMmFmNDc0LWVkMjgtNGYwMy1hMTdkLWNhOTE4YzY4NWY0NSIsIm5hbWUiOiJ1c2VyMiIsImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJzdGF0dXMiOiIwIiwiaWF0IjoxNjYxOTE1NjczLCJleHAiOjE2NjE5MTkyNzN9.OOeFKRapCOhoUDIDTvflLeJx5nHlbHihow52jAdn_M8


###

GET  http://localhost:7000/user/check
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwMmFmNDc0LWVkMjgtNGYwMy1hMTdkLWNhOTE4YzY4NWY0NSIsIm5hbWUiOiJ1c2VyMiIsImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJzdGF0dXMiOiIwIiwiaWF0IjoxNjYxOTE1NjczLCJleHAiOjE2NjE5MTkyNzN9.OOeFKRapCOhoUDIDTvflLeJx5nHlbHihow52jAdn_M8



###
GET  http://localhost:7000/user/users


# projects
###
POST http://localhost:7000/project/newproject
Content-Type: application/json

{
    "name":"projectcvccccvvHJ",
    "description":"This is project HN",
    "end_date": "Aug 12 2022",
    "assigned_user_email":"user2@gmail.com"
}

###
POST http://localhost:7000/project/assignNewProject
Content-Type: application/json

{   "name":"project 1",
    "user_id":"ffba3ac2-e3aa-47af-9575-79db177b2e80"}

###
POST http://localhost:7000/project/deleteProject
Content-Type: application/json

{
    "project_id":"e85a111f-c2a5-4b69-85e6-174306f21fd4"
    }

###
GET  http://localhost:7000/project/projects

###
GET  http://localhost:7000/project/project/user3@gmail.com

###
POST http://localhost:7000/project/complete
Content-Type: application/json

{
    "project_id":"b95de446-77b9-4084-9e5f-7f0b2073deec"
 }